package github

// Auto-generated by quicktype

type Chart struct {
	APIVersion   string   `yaml:"apiVersion"`
	Name         string   `yaml:"name"`
	Description  string   `yaml:"description"`
	Icon         string   `yaml:"icon"`
	Type         string   `yaml:"type"`
	Version      string   `yaml:"version"`
	AppVersion   string   `yaml:"appVersion"`
	Home         string   `yaml:"home"`
	Sources      []string `yaml:"sources"`
	Dependencies []struct {
		Name       string `yaml:"name"`
		Version    string `yaml:"version"`
		Repository string `yaml:"repository"`
		Condition  string `yaml:"condition"`
	} `yaml:"dependencies"`
}
