name: release
on:
  push:
    tags:
      - 'v*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
          check-latest: true
          cache: true
          cache-dependency-path: subdir/go.sum

      - name: Build
        run: go build -o autok3d-${{ env.RELEASE_VERSION }}.exe .\cmd\

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV


      - uses: ncipollo/release-action@v1
        with:
          artifacts: autok3d-${{ env.RELEASE_VERSION }}.exe